name: "RumiInventoryMenu"
version: "1.0"
main: "su.rumishistem.rumiinventorymenu.Main"
api-version: "1.21.5"

commands:
    menu:
        description: "メニューを管理する"
        usage: "/menu"
    openmenu:
        description: "メニューを開く"
        usage: "/menu name"
