enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 500
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - lunachat.join
  - lunachat.list
  - null
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.list
  - bungeecord.command.send
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 10000
timeout: 30000
player_limit: -1
prevent_proxy_connections: false
ip_forward: true
groups:
  Rumisan_:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 3beddf36-5264-4b4c-a7e5-67bb36c4af06
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:25555
    restricted: false
  main:
    motd: '&1Just another Waterfall - Forced Host'
    address: 192.168.0.144:25565
    restricted: false
